### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by wangshunping** [ChrisBeaumont/soupy#13]
Thanks for your package.

When I finished my setup, import soupy, there is error happened : 

> > > import soupy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/Library/Python/2.7/site-packages/soupy.py", line 139, in <module>
> > >     @six.python_2_unicode_compatible
> > > AttributeError: 'module' object has no attribute 'python_2_unicode_compatible'

Do you have any ideas to fix it ?

Thanks for your help.

**Comment by ChrisBeaumont** [comment]
Hi,

This message suggests that you need to `pip install --upgrade six`
